ekopsychologia/urls.py
from corecms.views.admin_form_generator import GenerateFormSendView
from corecms.views.site import MediaView, SearchView, TagResultView, ContactFormView
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from cms.views import GallerySetGlobalView
from website.views.site import ContentItemDetailView

urlpatterns = [
    url(r'^admin/cms/gallery/set-global/$', GallerySetGlobalView.as_view()),
    url(r'^admin/cms/', include('corecms.urls.admin', namespace='admin-corecms')),
    #url(r'^logout/$', 'django.contrib.auth.views.logout', {'next': '/'}, name="logout-url"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('website.urls.site', namespace='website')),
    url(r'^contact-form/$', ContactFormView.as_view(), name='corecms.contact-form'),
    url(r'^contact-form/send/(?P<form_id>\d+)/$', GenerateFormSendView.as_view(), name='corecms.formgen-send'),
    url(r'^tagi/(?P<tag>[\w-]+)/$', TagResultView.as_view(), name='corecms.tags.result'),
    url(r'^szukaj/$', SearchView.as_view(), name='search'),
    # url(r'^media/upload/(?P<hierarchy>[\-\/\w]+)/(?P<file_name>.*)$', MediaView.as_view()),
    url(r'^media/upload/(?P<hierarchy>.*)$', MediaView.as_view()),
    url(r'^(?P<hierarchy>[\-\/\w]+)/$', ContentItemDetailView.as_view(), name='content.detail'),
    url(r'^', include('corecms.urls.site', namespace='corecms')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

ekopsychologia/apps/cms/models.py
# -*- encoding: utf-8 -*-
from corecms.models.base_element import BaseElement
from corecms.models.config import ConfigCMSAbstract
from django.db import models
from positions.fields import PositionField
from corecms.models.site import SiteAbstract
from corecms.models.article import ArticleAbstract
from corecms.models.text_block import TextBlockAbstract
from corecms.models.media_file import AbstractMediaFile


class Site(SiteAbstract):

    old_cms_id = models.IntegerField(null=True, default=None)
    logo = models.ImageField("Logo", upload_to="site/images/", default=None, null=True, blank=True)
    execution_time = models.CharField(u"Czas realizacji", max_length=255, default="", blank=True)
    budget = models.CharField(u"Budżet całkowity", max_length=255, default="", blank=True)
    areas = models.ManyToManyField('self', verbose_name="Obszary działania", blank=True, related_name="+")
    url = models.URLField(u"Link", default="", blank=True)
    archived = models.BooleanField(u"Projekt archiwalny", default=False, blank=True)

    class Meta(SiteAbstract.Meta):
        abstract = False
        app_label = 'cms'

    @staticmethod
    def get_template_list():
        return [
            ('website/site/templates/site_obszary_dzialalnosci.html', u'Obszary działania (lista)'),
            ('website/site/templates/site_obszar.html', u'Obszar działania'),
            ('website/site/templates/site_contact.html', u'Kontakt'),
            ('website/site/templates/site_partnership.html', u'Wspolpraca'),
            ('website/site/templates/site_publication.html', u'Publikacje'),
            ('corecms/site/templates/articles_list_layout.html', u'Aktualności - lista'),

    ]

    def allow_redirect_to_children(self):
        if self.template == 'website/site/templates/site_obszary_dzialalnosci.html':
            return False
        return True

    def show_in_menu(self):
        if self.level < 2:
            return True
        return False


class Article(ArticleAbstract):
    alternative_url = models.CharField(u"Link alternatywny", max_length=255, default="", blank=True, help_text="Link na który bedzie wskazywała ten artykuł")
    old_cms_id = models.IntegerField(null=True, default=None)
    areas = models.ManyToManyField('cms.Site', verbose_name="Obszary działania", blank=True, related_name="+")

    class Meta(ArticleAbstract.Meta):
        app_label = 'cms'

    def get_absolute_url(self, category=None):
        if self.alternative_url != "":
            return self.alternative_url
        return super(Article, self).get_absolute_url(category)


class TextBlock(TextBlockAbstract):
    class Meta(TextBlockAbstract.Meta):
        app_label = 'cms'


class RelationArticleSite(models.Model):
    child = models.ForeignKey('cms.Article')
    parent = models.ForeignKey('cms.Site')
    position = PositionField(collection='parent')
    main = models.BooleanField(default=False)

    class Meta:
        app_label = 'cms'
        ordering = ['-id']
        unique_together = ("child", "parent")


class MediaFile(AbstractMediaFile):
    class Meta(AbstractMediaFile.Meta):
        abstract = False
        app_label = 'cms'


class ConfigCMS(ConfigCMSAbstract):

    events = models.IntegerField(verbose_name=u'Ilość wydarzeń', default=0) # 370
    participants = models.IntegerField(verbose_name=u'Uczestnicy', default=0) # 15000
    institutions = models.IntegerField(verbose_name=u'Inistytucji w Porozumieniu Karpackim', default=0) # 70
    experts = models.IntegerField(verbose_name=u'Ekspertów', default=0) # 300
    founds = models.IntegerField(verbose_name=u'Milionów złotych pozyskanych na działania', default=0) # 5
    projects = models.IntegerField(verbose_name=u'Zrealizowane Projekty', default=0) # 22

    class Meta(ConfigCMSAbstract.Meta):
        abstract = False
        app_label = 'cms'


class IsSite(models.Model):

    cms_id = models.IntegerField()
    is_site = models.BooleanField(default=False)

    class Meta():
        app_label = 'cms'


class GalleryDistinction(models.Model):

    gallery = models.ForeignKey('cms.Gallery')
    in_global = models.BooleanField(default=False)

    class Meta:
        app_label = 'cms'


class Founder(models.Model):
    site = models.ForeignKey(u"cms.Site")
    name = models.CharField(u"Nazwa", max_length=255)
    logo = models.ImageField("Logo", upload_to="site/founder/images/")
    url = models.URLField(u"Link", default="", blank=True)

ekopsychologia/apps/override_app/templates/corecms/admin/_render_submenu.html
{% load mptt_tags %}


{% if menu_nodes %}
    <div class="left-menu text-center" style="padding-bottom:10px;">
        {% if menu_nodes %}
            {% for node, structure in menu_nodes|tree_info %}
                {% if node.level > submenu_root.level and node.show_in_menu %}
                    {% if structure.new_level %}
                        <ul>
                        <li class="{% if node.get_absolute_url in request.breadcrumbs.urls %}active{% endif %}">{% else %}</li>
                        <li class="{% if node.get_absolute_url in request.breadcrumbs.urls %}active{% endif %}">{% endif %}
                {% ifequal node genre %}
                    <strong>{{ node }}</strong>
                {% else %}
                    <a href="{{ node.get_absolute_url }}" class="{% if node.get_absolute_url in request.breadcrumbs.urls %}active{% endif %}">{{ node|capfirst }}</a>
                {% endifequal %}
                {% for level in structure.closed_levels %}</li></ul>{% endfor %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endif %}

ekopsychologia/apps/override_app/templates/corecms/admin/_render_submenu_left.html
{% load mptt_tags %}


{% if menu_nodes %}
    <nav role="navigation" class="sub_menu navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="hidden-lg hidden-md hidden-sm hidden-xs "><h2><a
                    href="{{ category.get_root.get_absolute_url }}">{{ category.get_root }}</a></h2>
            </div>
        </div>
        <div id="navbarCollapse" class="navbar-collapse collapse navbar-left-menu">
            {% include 'corecms/admin/_render_submenu.html' %}
        </div>
    </nav>
{% endif %}

ekopsychologia/apps/override_app/templates/corecms/admin/_render_submenu_project.html
{% load thumbnail %}
{% load corecms_tags %}
{% load templatetags %}

   <a href="{{ category_project.get_absolute_url }}" class="">
<div class="page-title text-center project-icon clearfix{% if category_project.archived %} archived{% endif %}">
    {% if category_project.archived %}
                <span class="archived-wrapper-2">
                     <span class="icon-padlock-2">Projekt Archiwalny</span>
                </span>
                {% endif %}
        {% if category_project.logo %}

            {% thumbnail category_project.logo "200" seoname=category_project|addstr:"" as im %}
            <img src="{{ im.url }}" alt="{{ category_project }}">
            {% endthumbnail %}

        {% endif %}

</div>
   </a>

<div class="clearfix project-info-wrapper text-center">
    <div class="project-link-wrapper ">
        {% if category_project.url %}
    <div class="project-link-wrapper-border">

    <a class="project-link link-hover " href="{{ category_project.url }}">{{ category_project.url }}</a>

    </div>
        {% endif %}
        </div>

    <nav role="navigation" class="sub_menu navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="hidden-lg hidden-md hidden-sm hidden-xs "><h2><a
                    href="{{ category.get_root.get_absolute_url }}">{{ category.get_root }}</a></h2>
            </div>
        </div>
        <div id="navbarCollapse" class="navbar-collapse collapse navbar-left-menu">
            <div class="left-menu text-center" style="padding-bottom:10px;">
                <ul>
                    {% for node in category_project.children.published %}
                    <li class="{% if node.get_absolute_url in request.breadcrumbs.urls %}active{% endif %}">
                        <a href="{{ node.get_absolute_url }}" class="{% if node.get_absolute_url in request.breadcrumbs.urls %}active{% endif %}">{{ node|capfirst }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </nav>
{% if category_project.areas.all %}
    <div  class="animated fadeInUp obszary-projekty-wrapper">
        <div class="text-center founders-title">Obszary działania</div>
        {% include "corecms/site/_areas_2.html" with object=category_project only %}
    </div>
 {% endif %}

{% if category_project.founder_set.all %}
    <div class="animated fadeInUp project-founders project-founders-wrapper">
        <div class="text-center founders-title">Fundatorzy</div>
        <div class="founders-slider">
        {% for founder in category_project.founder_set.all %}
            <div class="text-center">
                <a href="{{ founder.url|default:"javascript:void(0)" }}" target="_blank">
                    {% thumbnail founder.logo "64" seoname=category_project|addstr:"" as im %}
                    <img src="{{ im.url }}" alt="{{ founder.name }}">
                    {% endthumbnail %}
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
 {% endif %}

    {% if category_project.execution_time %}
    <div class="animated fadeInUp czas-wrapper">
        <div class="text-center founders-title">Czas realizacji:</div>
        <div class="czas-realizacji-wrapper">
            {{ category_project.execution_time }}
        </div>
    </div>
    {% endif %}
    {% if category_project.budget %}
    <div class="animated fadeInUp budzet-wrapper">
        <div class="text-center founders-title">Budżet całkowity:</div>
        <div class="budzer-calkowity-wrapper">
            {{ category_project.budget }}
        </div>
    </div>
    {% endif %}

</div>
<script>
    $(function(){
        $('.founders-slider').slick({
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 3,
            arrows: false,
            dots: false,
            autoplay: true,
            autoplaySpeed: 2000
        });

        $('.project-info-wrapper .areas-list-slider').slick({
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 3,
            arrows: false,
            dots: false,
            autoplay: false,
            autoplaySpeed: 2500
        });

    })
</script>